apiVersion: argoproj.io/v1alpha1
kind: Application
# data:
#   timeout.reconciliation: "30s"      # To change the auto-sync check interval in ArgoCD, we can configure our custom time

metadata:
  name: root-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vinod1618/argocd.git
    targetRevision: main
    path: applications
  destination:
    server: https://kubernetes.default.svc  # current eks cluster
    namespace: argocd

  syncPolicy:
    automated:
      prune: true # if deleted in git, delete in k8s also
      selfHeal: true # if someone manually change through CLI, do the self heal.