apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vinod1618/argocd.git
    targetRevision: main
    path: namespaces
  destination:
    server: https://kubernetes.default.svc  # current eks cluster
    namespace: argocd

  syncPolicy:
    automated:
      prune: true # if deleted in git, delete in k8s also
      selfHeal: true # if someone manually change through CLI, do the self heal.